package com.pulseink.service.memory;

public enum InsightErrorCode {
    INSIGHT_SOURCE_NOT_READY,
    INSIGHT_NOT_FOUND,
    INSIGHT_MODEL_FAILURE,
    INSIGHT_MODEL_OUTPUT_INVALID,
    INSIGHT_DECISION_CONFLICT,
    INSIGHT_SEARCH_UNAVAILABLE,
    VALIDATION_ERROR
}
