package com.pulseink.service.campaign;

public enum RunEventType {
    EXECUTION_MODE_SELECTED,
    RUN_STATE_CHANGED,
    MODEL_ROUTE_SELECTED,
    DECISION_RECORDED,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    ARTIFACT_CREATED,
    APPROVAL_REQUIRED,
    RUNTIME_FAILED,
    PLAN_VALIDATED,
    TASK_STARTED,
    TASK_COMPLETED,
    REVIEW_ISSUE_CREATED,
    REPAIR_ROUND_STARTED,
    ARTIFACT_INVALIDATED,
    REPAIR_EXHAUSTED
}
