package com.pulseink.agent.api;

public enum AgentTerminalReason {
    SUCCEEDED,
    APPROVAL_REQUIRED,
    REPLAN_REQUESTED,
    HUMAN_INTERVENTION_REQUIRED,
    MODEL_CALL_LIMIT_EXCEEDED,
    TOOL_CALL_LIMIT_EXCEEDED,
    TOKEN_LIMIT_EXCEEDED,
    REACT_ROUND_LIMIT_EXCEEDED,
    DEADLINE_EXCEEDED,
    INVALID_MODEL_OUTPUT,
    MODEL_FAILURE,
    TOOL_FAILURE,
    CHECKPOINT_INVALID,
    RUNTIME_FAILED
}
